### ISSUE TITLE
Legacy Fabric example mod does not run properly on Apple Silicon (presumably only if LWGJL2 is required)

### ISSUE THREAD

**Issue by rinOfTheStars** [Legacy-Fabric/fabric-example-mod#27]
When attempting to run the example mod via native Java, a pre-launch crash occurs likely because the project doesn't have access to any native lwjgl binaries:
```
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.UnsatisfiedLinkError: Can't load library: /Volumes/cocona-external-hd/moddev/fabric-example-mod/.gradle/loom-cache/natives/1.8.9/liblwjgl.dylib
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /Volumes/cocona-external-hd/moddev/fabric-example-mod/.gradle/loom-cache/natives/1.8.9/liblwjgl.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at org.lwjgl.Sys$1.run(Sys.java:70)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at net.minecraft.client.MinecraftClient.getTime(MinecraftClient.java:2539)
	at net.minecraft.client.main.Main.main(Main.java:41)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 3 more
```
Meanwhile, if the project is run under x86-64 Java that has been translated via Rosetta 2, the game launches but _no game window is rendered._

Theoretically the fix for this would be to somehow make use of the https://github.com/orgs/MinecraftMachina project's native LWJGL binaries in the buildscript, though how to do this w.o outright rehosting them on a maven I'm not sure of.

**Comment by Wyvest** [comment]
add this to your build.gradle

loom {
    runConfigs.named("client")
        vmArgs.remove("-XstartOnFirstThread")
    }
}

to fix lwjgl with rosetta

(can’t do it as a codeblock, on mobile)

**Comment by rinOfTheStars** [comment]
Thanks. Figured out how to get the dependency binaries brought over as well (by manually unpacking them from the MinecraftMachina arm64 compiled jars)—I'll keep this open since it should be possible to add a check in the build.gradle to run that if macOS is present. 

Edit: seems to not work, vmArgs isn't a property that exists, seemingly 
Edit 2:
```
 if(System.getProperty("os.name").toLowerCase().contains("mac")) {
        runConfigs.named("client").get().getVmArgs().remove("-XstartOnFirstThread")
    }
```

**Comment by thecatcore** [comment]
Is it possible for you to try again with the current version of example mod?
We now provide our own version of LWJGL 2 with a few fixes from multiple forks.
Tho I don't have a Mac to test those fixes on, so report any issue/crash you have with it, here.
